# Generated by Django 2.0.6 on 2018-06-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='auher',
            new_name='auther',
        ),
    ]
